### ISSUE TITLE
encrypted weechat homedir failing on install hook

### ISSUE THREAD

**Issue by afreiberger** [alchemy-charmers/layer-weechat#2]
encfs failing with non-empty directory:

unit-weechat-0: 14:00:11 DEBUG unit.weechat/0.install fuse: mountpoint is not empty
unit-weechat-0: 14:00:11 DEBUG unit.weechat/0.install fuse: if you are sure this is safe, use the 'nonempty' mount option
unit-weechat-0: 14:00:11 DEBUG unit.weechat/0.install fuse failed.  Common problems:
unit-weechat-0: 14:00:11 DEBUG unit.weechat/0.install  - fuse kernel module not installed (modprobe fuse)
unit-weechat-0: 14:00:11 DEBUG unit.weechat/0.install  - invalid options -- see usage message
unit-weechat-0: 14:00:11 ERROR unit.weechat/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-weechat-0/.venv/lib/python3.6/site-packages/charms/reactive/__init__.py", line 73, in main
    bus.dispatch(restricted=restricted_mode)
  File "/var/lib/juju/agents/unit-weechat-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 390, in dispatch
    _invoke(other_handlers)
  File "/var/lib/juju/agents/unit-weechat-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 359, in _invoke
    handler.invoke()
  File "/var/lib/juju/agents/unit-weechat-0/.venv/lib/python3.6/site-packages/charms/reactive/bus.py", line 181, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-weechat-0/charm/reactive/weechat.py", line 42, in install_weechat
    setup_encfs()
  File "/var/lib/juju/agents/unit-weechat-0/charm/reactive/weechat.py", line 28, in setup_encfs
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'echo "*SECRET*" | encfs -S --standard --public /home/weechat/.encweechat /home/weechat/.weechat' returned non-zero exit status 1.

Contents of homedir upon inspection:

root@juju-49e074-0-lxd-0:/home# find
.
./weechat
./weechat/.profile
./weechat/.bash_logout
./weechat/.bashrc
./weechat/.encweechat
./weechat/.encweechat/9XVD4z1RVvw843lwQVBOjoMH
./weechat/.encweechat/9XVD4z1RVvw843lwQVBOjoMH/qCjJlABfkhkVJiSPUJyqaTDl
./weechat/.encweechat/9XVD4z1RVvw843lwQVBOjoMH/HRKg,RvHGTjPHdka9u0gIBv,
./weechat/.encweechat/9XVD4z1RVvw843lwQVBOjoMH/HRKg,RvHGTjPHdka9u0gIBv,/IRa2t6,vb18d-gRGeRCSiXy5
./weechat/.encweechat/upksGvuFGUtdIPreX4pKCtey
./weechat/.encweechat/bLZTI5M3hjjZgwVfrsDjtWAZ
./weechat/.encweechat/bLZTI5M3hjjZgwVfrsDjtWAZ/vEzQbj,EZ26MFRR5THAR9v53
./weechat/.encweechat/V3wA7y8f8ayDpqOt1e5XIixA
./weechat/.encweechat/e-T0viC9UH8iUim9CxASNLE1
./weechat/.encweechat/qJF4anK4omikODzWZKgpkHqs
./weechat/.encweechat/LI3vBLYEh1FptsgrbD-Oznm6
./weechat/.encweechat/ypnC2njm0u5mP8PlGFpwM7MD
./weechat/.encweechat/SIlcyBNAm5XP439m9xMsM04S
./weechat/.encweechat/CLRJ06DIh69jBbBprJguWf2Y
./weechat/.encweechat/CLRJ06DIh69jBbBprJguWf2Y/DhXfEvBrUgynh3gUWFwrrg-m
./weechat/.encweechat/T,lM21q4oNsKK9T1uFQtD-FS
./weechat/.encweechat/sxwjKOlrFQk2uurLwCzBhJpy
./weechat/.encweechat/FY37hmC6q0xxScer81dUDYdj
./weechat/.encweechat/FY37hmC6q0xxScer81dUDYdj/JAM2g2PbobF6IXCctTycQ0fQ
./weechat/.encweechat/6eX3K3Ab6TxxoiDSQaF8nw1b
./weechat/.encweechat/JA0PQv40Iwi0GIJWP1RHGvYJ
./weechat/.encweechat/JA0PQv40Iwi0GIJWP1RHGvYJ/gnPJu0ZD8n9GWjDRdUc7PoAd
./weechat/.encweechat/JA0PQv40Iwi0GIJWP1RHGvYJ/gnPJu0ZD8n9GWjDRdUc7PoAd/C9uo65rad5h7tL,WmjGnb0Pc
./weechat/.encweechat/JA0PQv40Iwi0GIJWP1RHGvYJ/trB0uZDynVbjfeZlPdVM6TuZ
./weechat/.encweechat/F3bE,U5AV1FKERm2h1qlOYNs
./weechat/.encweechat/F3bE,U5AV1FKERm2h1qlOYNs/oXYukLYHTvAzJVEkAhjOJKtd
./weechat/.encweechat/Rw8MZRFPHhNV3SKahb9xExsI
./weechat/.encweechat/Rw8MZRFPHhNV3SKahb9xExsI/L6jVCHNY8jvPfx8W8B5IPK2P
./weechat/.encweechat/Rw8MZRFPHhNV3SKahb9xExsI/L6jVCHNY8jvPfx8W8B5IPK2P/qaqnT2BGdXaYZoa54mg2mw6LXyxyv9ZELccWY4IqrR5kx0
./weechat/.encweechat/Rw8MZRFPHhNV3SKahb9xExsI/L6jVCHNY8jvPfx8W8B5IPK2P/JFaePaBUUA5K7CZHYDRKbM94
./weechat/.encweechat/Rw8MZRFPHhNV3SKahb9xExsI/OFbJz2-UvmlhxxUtoMSsnlO9
./weechat/.encweechat/Rw8MZRFPHhNV3SKahb9xExsI/S6GHJvrFu9prhM46bPyF7610t0ZCRPNA3ymrQTrn9,A3A-
./weechat/.encweechat/EgZPOqfwx0GpSUXNJWQhBuBu
./weechat/.encweechat/.encfs6.xml
./weechat/.encweechat/wTQxqBaRBg5QEkwyJloHdmOL
./weechat/.encweechat/RA7CJoEuMtWT3lWA6B,YlbNK
./weechat/.encweechat/yqW0CjFzPWpFBvx,h2t04oM7
./weechat/.encweechat/ahfaM-RnRuFKTJzhcgsQUdTq
./weechat/.encweechat/mJe6q-toSn6QoXwCemcWcMfr
./weechat/.encweechat/mJe6q-toSn6QoXwCemcWcMfr/6TYjc2Azobb1nJXINGVC-VXt
./weechat/.encweechat/mJe6q-toSn6QoXwCemcWcMfr/7pSu8Wq8a0U3cRP7EsrBaa3w
./weechat/.encweechat/mJe6q-toSn6QoXwCemcWcMfr/I3ME7ysPPF33S74BwpvPiG7y
./weechat/.encweechat/mJe6q-toSn6QoXwCemcWcMfr/M4VqQnXpk3cFNNRBEs8cE6KB4pV0husBHvC1I,QmJG234-
./weechat/.encweechat/mJe6q-toSn6QoXwCemcWcMfr/7RnsYbf4p2mYlD4AfrEUj9C,yQX36B7DiIL6AmyN-wiFA0
./weechat/.encweechat/6TUEcX88nGtSSxGbBwGMtMoe
./weechat/.encweechat/6TUEcX88nGtSSxGbBwGMtMoe/fFe1DIiPD30qysjpdRSq1xeAq1Vp3s3anQVstCUyHvAZb1
./weechat/.encweechat/LnDHYb7A4EPn8QWjYqxjnpYu
./weechat/.encweechat/9OgFtk75Gj5mK0GFpDulN5t,
./weechat/.encweechat/q-OV-FWdERF,eVvr67llBPfF
./weechat/.weechat
./weechat/.weechat/perl
./weechat/.weechat/perl/spell_menu.pl
./weechat/.weechat/perl/autoload
./weechat/.weechat/perl/autoload/spell_menu.pl
./weechat/.weechat/plugins.conf
./weechat/.weechat/guile
./weechat/.weechat/guile/autoload
./weechat/.weechat/weechat.log
./weechat/.weechat/autosort.conf
./weechat/.weechat/charset.conf
./weechat/.weechat/exec.conf
./weechat/.weechat/weechat.conf
./weechat/.weechat/relay.conf
./weechat/.weechat/lua
./weechat/.weechat/lua/autoload
./weechat/.weechat/alias.conf
./weechat/.weechat/sec.conf
./weechat/.weechat/ssl
./weechat/.weechat/ssl/relay.pem
./weechat/.weechat/logger.conf
./weechat/.weechat/ruby
./weechat/.weechat/ruby/autoload
./weechat/.weechat/ruby/autoload/substitution.rb
./weechat/.weechat/ruby/substitution.rb
./weechat/.weechat/tcl
./weechat/.weechat/tcl/autoload
./weechat/.weechat/python
./weechat/.weechat/python/autoload
./weechat/.weechat/python/autoload/buffer_autoclose.py
./weechat/.weechat/python/autoload/autosort.py
./weechat/.weechat/python/autosort.py
./weechat/.weechat/python/buffer_autoclose.py
./weechat/.weechat/irc.conf
./weechat/.weechat/xfer.conf
./weechat/.weechat/xfer
./weechat/.weechat/script.conf
./weechat/.weechat/aspell.conf
./weechat/.weechat/script
./weechat/.weechat/script/buffers.pl
./weechat/.weechat/script/plugins.xml.gz
./weechat/.weechat/script/pyrnotify.py
./weechat/.weechat/script/colorize_nicks.py
./weechat/.weechat/script/buffer_autoset.py
./weechat/.weechat/logs
./weechat/.weechat/logs/core.weechat.weechatlog
./weechat/.weechat/trigger.conf
./weechat/.weechat/fifo.conf
./weechat/.weechat/buflist.conf
./ubuntu
./ubuntu/.ssh
./ubuntu/.ssh/authorized_keys
./ubuntu/.profile
./ubuntu/.bash_logout
./ubuntu/.bashrc

It appears that the weechat screen session is started before encrypting the user homedir.

**Comment by afreiberger** [comment]
This is actually caused by a failure in weechat config when you have $'s in your configs.  using shell to push the data into the file from the config will really jam up the works when you start having advanced weechat configs.

subprocess.CalledProcessError: Command 'echo */set autosort.v3.helpers = "{ "chan1": "${if:${window.buffer.name}==#chan1}", "core_last": "${if:${buffer.full_name}==core.weechat}", }" > /home/weechat/.weechat/weechat_fifo' returned non-zero exit status 2.

The issue is bad BASH substitution.

We need to change the charm to directly open and write the lines into the fifo, and also trap this exception and just spit out "can't apply config line X" into log files and block on bad config rather than re-trying to encrypt the filesystem.  The issue is encfs worked fine, then the config failed during the install hook, and the install hook re-runs and it's already encrypted and full of files, and it's trying to re-encrypt.  So, a trap around "already configured as encfs" in the install routine would help as well.

**Comment by chris-sanders** [comment]
Nice catch, you're right that would be a better way to handle the fifo and catching the already mounted condition to allow re-trying a failed install is a good idea too.
